### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by ttzl279** [simonflueckiger/tesserocr-windows_build#11] opened 2020-01-20 06:13 UTC
I can not use this out of the box with Python 3.8. I've fiddled around for a while now, but it seems without being able to compile the libraries myself, it's not going to work.

Any chance of adding out-of-the-box Python 3.8 support?

**Comment by GZLHZ** [comment] 2020-02-04 13:31
same request, waiting support.

**Comment by literence** [comment] 2020-02-20 04:43
waiting support

**Comment by PM-yanmao** [comment] 2020-02-29 09:47
waiting support

**Comment by PM-yanmao** [comment] 2020-03-19 03:27
waiting support

**Comment by lockieRichter** [comment] 2020-05-08 03:55
Agree.

**Comment by EhsanKia** [comment] 2020-05-22 05:54
Has anyone figured out how to compile it for 3.8?

**Comment by tb102122** [comment] 2020-07-02 03:07
any updates? having the same issue.

**Comment by ApurvaDani** [comment] 2020-08-24 12:07
Require support for 3.8

**Comment by wjx0912** [comment] 2020-09-10 00:34
waiting support

**Comment by 2press** [comment] 2020-10-10 09:06
@simonflueckiger Can you help us out?

**Comment by Callan-Git** [comment] 2021-02-01 01:08
Require support for 3.9

**Comment by bytetriper** [comment] 2022-02-07 13:53
same request but for 3.10

**Comment by simonflueckiger** [comment] 2022-02-13 17:24
Sorry for the very long wait everyone. The old build pipeline was in dire need of a proper refactor. The build of Tesseract was depending on [CPPAN](https://github.com/cppan/cppan) which is not maintained anymore. Instead of opting for [Software Network](https://github.com/SoftwareNetwork/sw) (the successor of CPPAN), I decided to go with the more tried and tested [vcpkg](https://github.com/microsoft/vcpkg). This should now make it really easy for me to update and maintain the Windows binaries for new builds of tesserocr and Tesseract.

You can find the latest release in [tesserocr v2.5.2 (tesseract 4.1.1)](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.5.2-tesseract-4.1.1) which is built for Python 3.6, 3.7, 3.8, 3.9, 3.10. I know that for most of you this probably comes too late, sorry about that. Nonetheless, I would very much appreciate if any of you could give it a test-drive and report back here if it works as intended so I can close this issue.

**Comment by tb102122** [comment] 2022-02-14 04:26
@simonflueckiger see details in #12

**Closed** 2023-01-19 00:11 UTC
